/**
 * Robust tiled watermark for free-tier PDF downloads.
 *
 * Why this is hard to remove:
 *  1. The watermark is a TILED SVG pattern rendered as a CSS `background-image`
 *     on the page itself. It is not a single text node a watermark-remover can
 *     locate and delete — it's hundreds of tiny rotated text instances baked
 *     into the page's raster.
 *  2. Multiple repetitions overlap with content. To remove them cleanly a
 *     remover would need to reflow the resume itself.
 *  3. Also emitted via PDF document metadata (`Title`, `Subject`, `Keywords`,
 *     `Producer`) — those persist even after most online "watermark removers"
 *     run and let us trace pirated copies back.
 *  4. A bottom-of-page banner is also rendered with `position: fixed` so it
 *     repeats on every page Puppeteer prints.
 *
 * What this is NOT: bullet-proof DRM. A sufficiently determined user with
 * Photoshop / Adobe Acrobat Pro can still get rid of it. The goal is to make
 * removal more effort than paying ₹149.
 */

const WATERMARK_TEXT = 'RESUMEMATE.IN  ·  FREE PREVIEW  ·  UPGRADE TO REMOVE';

/**
 * Returns a CSS-ready `data:image/svg+xml` URL for the tiled watermark.
 * Tile size is ~340×220 px so each Letter-size page gets ~9 instances
 * staggered diagonally, all at low opacity.
 */
export function watermarkDataUrl(opts: { opacity?: number; color?: string } = {}): string {
  const opacity = opts.opacity ?? 0.07;
  const color = opts.color ?? '#1f2937';

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="340" height="220" viewBox="0 0 340 220">
    <defs>
      <pattern id="diag" x="0" y="0" width="340" height="220" patternUnits="userSpaceOnUse">
        <g transform="rotate(-30 170 110)" fill="${color}" fill-opacity="${opacity}" font-family="Helvetica, Arial, sans-serif" font-weight="700" font-size="13" letter-spacing="2">
          <text x="-20" y="40">${WATERMARK_TEXT}</text>
          <text x="-20" y="120">${WATERMARK_TEXT}</text>
          <text x="-20" y="200">${WATERMARK_TEXT}</text>
        </g>
      </pattern>
    </defs>
    <rect width="100%" height="100%" fill="url(#diag)"/>
  </svg>`;

  // Encode for safe use as a CSS url(...) value
  const encoded = encodeURIComponent(svg).replace(/'/g, '%27').replace(/"/g, '%22');
  return `data:image/svg+xml;charset=UTF-8,${encoded}`;
}

/** CSS rule string that applies the watermark to a container. */
export function watermarkCss(opts: { opacity?: number; color?: string } = {}): string {
  const url = watermarkDataUrl(opts);
  return `
    .rm-watermark-host {
      position: relative;
    }
    .rm-watermark-host::before {
      content: '';
      position: absolute;
      inset: 0;
      background-image: url("${url}");
      background-repeat: repeat;
      pointer-events: none;
      z-index: 9999;
    }
    .rm-watermark-banner {
      position: fixed;
      bottom: 4px;
      left: 0;
      right: 0;
      text-align: center;
      font-family: Helvetica, Arial, sans-serif;
      font-size: 8px;
      letter-spacing: 1.5px;
      color: rgba(31, 41, 55, 0.55);
      text-transform: uppercase;
      pointer-events: none;
      z-index: 9999;
    }
  `;
}

/** HTML snippet appended after the resume content. Renders the footer banner. */
export const WATERMARK_FOOTER_HTML = `<div class="rm-watermark-banner">Free Preview · Made with ResumeMate.in · Upgrade to remove this banner</div>`;

/** PDF metadata stamped onto every free download (read by most PDF viewers). */
export const WATERMARK_PDF_METADATA = {
  title: 'ResumeMate Free Preview',
  subject: 'Watermarked preview generated by ResumeMate.in',
  keywords: 'resumemate, free preview, watermarked, upgrade to remove',
  producer: 'ResumeMate (Free Tier)',
  creator: 'ResumeMate.in',
};
